# Analisi differenziale {#sec-deg}

```{r}
#| results: "asis"
#| echo: false
source("_common.R")
```

::: {.content-hidden when-meta="features.advanced_analysis"}
Benvenuti alla seconda parte del corso, dove ci addentreremo nel cuore dell'analisi RNA-seq: l'analisi dell'espressione differenziale!

Dopo aver accuratamente preparato e esplorato i nostri dati, siamo pronti per applicare il potente framework statistico offerto da DESeq2 per identificare i geni che mostrano cambiamenti significativi di espressione tra le diverse condizioni sperimentali.

In questa parte del corso, ci concentreremo sui seguenti aspetti fondamentali:

-   **Normalizzazione**: Vedremo come DESeq2 normalizza i dati di conteggio per tenere conto delle differenze nella dimensione della libreria e di altri fattori tecnici, garantendo un confronto accurato tra i campioni.

-   **Modellazione Statistica**: Vedremo il modello statistico alla base di DESeq2 che si basa sulla distribuzione binomiale negativa per modellare i dati di conteggio e stimare la variabilità tra i replicati.

-   **Testing**: Impareremo come DESeq2 applica test statistici per identificare i geni differenzialmente espressi, tenendo conto del disegno sperimentale e controllando il tasso di falsi positivi.

Attraverso questi passaggi, saremo in grado di ottenere una **lista di geni differenzialmente espressi**, completa di stime dell'effetto (log2 fold change) e significatività statistica (p-value aggiustati).

Nei capitoli successivi, approfondiremo l'esplorazione dei risultati per contrasti specifici, la visualizzazione dei dati e l'interpretazione biologica dei risultati.
:::


::: {.content-hidden unless-meta="features.advanced_analysis"}
-   **Normalizzazione**:  Il processo di normalizzazione in DESeq2 corregge le differenze nella dimensione della libreria e altri fattori tecnici, assicurando un confronto accurato tra i campioni.

-   **Modellazione Statistica**: DESeq2 utilizza un modello statistico basato sulla distribuzione binomiale negativa per modellare i dati di conteggio e stimare la variabilità tra i replicati.

-   **Testing**:  L'analisi differenziale di espressione genica in DESeq2 si basa su test statistici che tengono conto del disegno sperimentale e controllano il tasso di falsi positivi.

Attraverso queste fasi, si otterrà una **lista di geni differenzialmente espressi**, comprensiva di stime dell'effetto (log2 fold change) e significatività statistica (p-value aggiustati).

:::